language:
  - bash

services:
  - docker

sudo: true

jobs:
  include:
    - stage: build
      script: ./ci/bin/docker_build_and_push.sh 2/alpine scala scala:2 scala:2.13 scala:2.13.0 scala:2.13.0-alpine scala:2.13-1.2.8 scala:2.13.0-1.2.8-alpine

